# Generated by Django 3.0.3 on 2020-03-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventure.Monster'),
        ),
        migrations.AddField(
            model_name='room',
            name='x_coor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coor',
            field=models.IntegerField(default=0),
        ),
    ]
