# Generated by Django 3.0.3 on 2020-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200302_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='honey',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=5),
        ),
    ]
