# Generated by Django 3.0.3 on 2020-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200302_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='monster',
            field=models.IntegerField(default=0),
        ),
    ]
